# -*- coding: utf-8 -*-
"""DataScience Final Proj2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-wYfsB6TDWOU1cXOLtXsE5G_t0Vx6B6a

## Kernel PCA

### Importing Libaries
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np

from sklearn.decomposition import KernelPCA

from matplotlib import pyplot as plt
# %matplotlib inline

"""#### Lets generate some non linear data"""

x1 = (np.random.rand(200) )
x2 = (np.random.rand(200) -0.5) 
y1 = np.sin(x1*np.pi) - 0.25
y2 = np.sin((x2-0.5)*np.pi) + 0.25

plt.plot(x1,y1,"^",color="red")
plt.plot(x2,y2,"o",color="blue")
plt.title("Non-Linear Data")
plt.show()

data = np.vstack((np.append(x1,x2),np.append(y1,y2))).T

kPCA = KernelPCA(kernel="poly")
finalData = kPCA.fit_transform(data)

plt.plot(finalData[:200,0],finalData[:200,1],"^",color="red")
plt.plot(finalData[200:,0],finalData[200:,1],"o",color="blue")